#!/bin/bash

# Check the operating system
OS_NAME=$(uname -s)
OS_VERSION=""

if [[ "$OS_NAME" == "Linux" ]]; then
    if command -v lsb_release &>/dev/null; then
        OS_VERSION=$(lsb_release -rs)
    elif [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS_VERSION=$VERSION_ID
    fi
    if [[ "$OS_VERSION" != "22.04" ]]; then
        echo "Warning: This script has only been tested on Ubuntu 22.04"
        echo "Your system is running Ubuntu $OS_VERSION."
        read -p "Do you want to continue anyway? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Installation cancelled."
            exit 1
        fi
    fi
else
    echo "Unsupported operating system: $OS_NAME"
    exit 1
fi

echo "Operating system check passed: $OS_NAME $OS_VERSION"

# Resolve script directory so files can be referenced reliably
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"

# Conda environment yaml file (canonical name)
CONDA_ENV_FILE="$SCRIPT_DIR/conda_environment.yaml"
if [[ ! -f "$CONDA_ENV_FILE" ]]; then
    echo "Error: conda environment yaml not found: $CONDA_ENV_FILE"
    exit 1
fi

# Function to create environment
create_environment() {
    local CONDA_CMD=$1
    local ENV_NAME=$2

    # Deactivate current environment if any (use conda deactivate for both conda and mamba)
    conda deactivate 2>/dev/null || true

    # Remove existing environment if it exists
    if $CONDA_CMD env list | grep -q "^$ENV_NAME "; then
        echo "Removing existing environment '$ENV_NAME'..."
        $CONDA_CMD env remove -n "$ENV_NAME" -y
    fi

    # Create new environment from conda_environment.yaml
    $CONDA_CMD env create -f "$CONDA_ENV_FILE" -n "$ENV_NAME"

    echo "$CONDA_CMD environment '$ENV_NAME' created from: $CONDA_ENV_FILE"

    echo -e "[INFO] Created $CONDA_CMD environment named '$ENV_NAME'.\n"
    echo -e "\t\t1. To activate the environment, run:                $CONDA_CMD activate $ENV_NAME"
    echo -e "\t\t2. To install all dependencies, run:                bash $SCRIPT_NAME --install"
    echo -e "\t\t3. To deactivate the environment, run:              conda deactivate"
    echo -e "\n"
}

write_sitecustomize() {
    local PY_VER
    PY_VER="$(python -c 'import sys; print(f"python{sys.version_info.major}.{sys.version_info.minor}")')"
    local SITE_DIR="${CONDA_PREFIX}/lib/${PY_VER}/site-packages"
    local TARGET="${SITE_DIR}/sitecustomize.py"

    if [[ -f "$TARGET" ]] && grep -q "RTLD_GLOBAL" "$TARGET" 2>/dev/null; then
        echo "[sitecustomize] Already configured."
        return
    fi
    echo "[sitecustomize] Writing libstdc++ preloader → $TARGET"
    cat > "$TARGET" << 'PYEOF'
"""
Preload conda's libstdc++ so C++ extensions compiled with GCC 14+ can find
CXXABI_1.3.15 symbols without relying on the system's older libstdc++.
Auto-generated by setup_env.sh.
"""
import ctypes
import os

prefix = os.environ.get("CONDA_PREFIX")
if prefix:
    p = os.path.join(prefix, "lib", "libstdc++.so.6")
    if os.path.exists(p):
        try:
            ctypes.CDLL(p, mode=ctypes.RTLD_GLOBAL)
        except Exception:
            pass
PYEOF
}

# conda installs a udev/ directory that confuses ctypes.util.find_library("udev"),
# causing pyudev/xensesdk to crash with "OSError: .../lib/udev: Is a directory".
fix_udev_discovery() {
    if [[ -d "${CONDA_PREFIX}/lib/udev" ]]; then
        echo "[udev] Renaming ${CONDA_PREFIX}/lib/udev to avoid pyudev clash..."
        local target="${CONDA_PREFIX}/lib/udev.rules.d"
        [[ -e "$target" ]] && target="${target}.bak.$(date +%s)"
        mv "${CONDA_PREFIX}/lib/udev" "$target" || true
    fi
    if [[ -e "${CONDA_PREFIX}/lib/libudev.so.1" && ! -e "${CONDA_PREFIX}/lib/libudev.so" ]]; then
        ln -s libudev.so.1 "${CONDA_PREFIX}/lib/libudev.so" || true
    fi
}

# ── Hardware module: ARX5 ─────────────────────────────────────────────────────

install_arx5() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " ARX5 SDK  →  pyarx"
    echo "══════════════════════════════════════════"

    local SDK_DIR="$PROJECT_ROOT/third_party/ARX5_SDK"
    if [[ ! -d "$SDK_DIR" ]]; then
        echo "ERROR: $SDK_DIR not found."
        echo "  Run: git submodule update --init third_party/ARX5_SDK"
        return 1
    fi

    # The PyPI spdlog package installs conflicting C++ headers — remove it first.
    uv pip uninstall spdlog 2>/dev/null || true

    bash "$SDK_DIR/build_python.sh"

    # Set real-time scheduling capability for Python (required by ARX5 SDK)
    echo "[arx5] Setting real-time scheduling capability for Python..."
    PYTHON_REAL_PATH=$(readlink -f "$CONDA_PREFIX/bin/python")
    sudo setcap cap_sys_nice=ep "$PYTHON_REAL_PATH"
    echo "[arx5] Real-time scheduling capability set for: $PYTHON_REAL_PATH"

    write_sitecustomize
    echo "[arx5] Done. Verify with: python -c 'import pyarx; print(pyarx)'"
}

# ── Hardware module: Flexiv ───────────────────────────────────────────────────

install_flexiv() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " libpyflexiv  →  flexiv_rt"
    echo "══════════════════════════════════════════"

    local LIB_DIR="$PROJECT_ROOT/third_party/libpyflexiv"
    local RDK_INSTALL="${RDK_INSTALL_PATH:-$HOME/rdk_install}"

    if [[ ! -d "$LIB_DIR" ]]; then
        echo "ERROR: $LIB_DIR not found."
        echo "  Run: git submodule update --init third_party/libpyflexiv"
        return 1
    fi

    # Stage 1: build ~/rdk_install (only if not already present)
    if [[ ! -f "$RDK_INSTALL/include/flexiv/rdk/robot.hpp" ]]; then
        echo ""
        echo "[flexiv] ~/rdk_install not found or incomplete. Build it first:"
        echo ""
        echo "  cd third_party/libpyflexiv"
        echo "  git submodule update --init flexiv_rdk"
        echo "  cd flexiv_rdk/thirdparty"
        echo "  bash build_and_install_dependencies.sh ~/rdk_install \$(nproc)"
        echo "  cd ../.. && mkdir -p build && cd build"
        echo "  cmake .. -DCMAKE_INSTALL_PREFIX=~/rdk_install -DCMAKE_PREFIX_PATH=~/rdk_install"
        echo "  cmake --build . --target install --config Release -j\$(nproc)"
        echo ""
        echo "Then rerun: bash setup_env.sh --install"
        return 1
    fi

    # Stage 2: build Python bindings (inside conda env)
    # IMPORTANT: only pass ~/rdk_install as CMAKE_PREFIX_PATH.
    # Do NOT include $CONDA_PREFIX — conda contains a different spdlog version
    # that will cause header conflicts (see third_party/libpyflexiv/README.md).
    local BUILD_DIR="$LIB_DIR/build"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    cmake \
        -S "$LIB_DIR" \
        -B "$BUILD_DIR" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="$RDK_INSTALL" \
        -DPython3_EXECUTABLE="$(which python)"

    cmake --build "$BUILD_DIR" -j"$(nproc)"

    uv pip install -e "$LIB_DIR" --no-build-isolation

    write_sitecustomize
    echo "[flexiv] RT SDK done. Verify with: python -c 'import flexiv_rt; print(flexiv_rt)'"

    # Install Flexiv NRT Python SDK from PyPI
    echo ""
    echo "[flexiv] Installing NRT SDK (flexivrdk)..."
    uv pip install "flexivrdk"
    echo "[flexiv] NRT SDK done. Verify with: python -c 'import flexivrdk; print(flexivrdk)'"
}

# ── Hardware module: Pico4 ────────────────────────────────────────────────────

install_pico4() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " XenseVR-PC-Service  →  xensevr_pc_service_sdk"
    echo "══════════════════════════════════════════"

    local SDK_SRC="$PROJECT_ROOT/third_party/XenseVR-PC-Service"
    local PYBIND_DIR="$PROJECT_ROOT/src/lerobot/teleoperators/pico4/xensevr-pc-service-pybind"

    if [[ ! -d "$SDK_SRC" ]]; then
        echo "ERROR: $SDK_SRC not found."
        echo "  Run: git submodule update --init third_party/XenseVR-PC-Service"
        return 1
    fi

    # Build the C SDK
    bash "$SDK_SRC/RoboticsService/PXREARobotSDK/build.sh"

    # Copy headers and .so into the pybind directory
    local CSDK_DIR="$SDK_SRC/RoboticsService/PXREARobotSDK"
    mkdir -p "$PYBIND_DIR/include" "$PYBIND_DIR/lib"
    cp "$CSDK_DIR/PXREARobotSDK.h" "$PYBIND_DIR/include/"
    cp -r "$CSDK_DIR/nlohmann" "$PYBIND_DIR/include/"
    cp "$CSDK_DIR/build/libPXREARobotSDK.so" "$PYBIND_DIR/lib/"

    # Build and install the Python bindings
    pushd "$PYBIND_DIR" > /dev/null
    rm -rf build *.egg-info
    uv pip uninstall xensevr_pc_service_sdk 2>/dev/null || true
    uv pip install . --no-build-isolation
    popd > /dev/null

    echo "[pico4] Done. Verify with: python -c 'import xensevr_pc_service_sdk; print(xensevr_pc_service_sdk)'"
}

# ── Hardware module: Xense ────────────────────────────────────────────────────

install_xense() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " xensesdk + XGripper (submodules)"
    echo "══════════════════════════════════════════"

    local SDK_DIR="$PROJECT_ROOT/third_party/xensesdk"
    local GRIPPER_DIR="$PROJECT_ROOT/third_party/XGripper"
    local XU_DIR="$SDK_DIR/xense_xu/cpp"

    if [[ ! -d "$SDK_DIR" ]]; then
        echo "ERROR: $SDK_DIR not found."
        echo "  Run: git submodule update --init third_party/xensesdk"
        return 1
    fi
    if [[ ! -d "$GRIPPER_DIR" ]]; then
        echo "ERROR: $GRIPPER_DIR not found."
        echo "  Run: git submodule update --init third_party/XGripper"
        return 1
    fi
    if [[ ! -d "$XU_DIR" ]]; then
        echo "ERROR: $XU_DIR not found."
        echo "  Run: git submodule update --init third_party/xensesdk"
        return 1
    fi

    fix_udev_discovery

    # XGripper bundles libsurvive which links against libhidapi-libusb.
    # The conda cross-compiler uses its own sysroot and cannot find system hidapi,
    # so the C library (libhidapi) must be present in the conda environment.
    if ! compgen -G "${CONDA_PREFIX}/lib/libhidapi*.so*" > /dev/null 2>&1; then
        echo "[xense] hidapi not found in conda env — installing via conda-forge..."
        ${CONDA_CMD:-mamba} install -c conda-forge libhidapi -y
    fi

    # Install xensesdk dependencies explicitly
    uv pip install \
        "numpy>=1.26.4,<2.3.0" \
        "opencv-python>=4.10" \
        "pillow>=12.0" \
        "cryptography>=46.0" \
        "PyYAML>=6.0" \
        "h5py>=3.10" \
        "scipy>=1.14" \
        "lz4>=4.0" \
        "psutil>=7.0" \
        "spdlog>=2.0" \
        "pyudev; platform_system=='Linux'"
    # Install xensesdk from local submodule
    uv pip install -e "$SDK_DIR"
    echo "[xense] Building pyxensexu companion module..."
    bash "$XU_DIR/build_python.sh"
    # Install XGripper from local submodule (package name: xgripper)
    uv pip install -e "$GRIPPER_DIR" --no-deps
    # xensesdk requires a specific av version
    uv pip install av==15.1.0

    local PY_VER
    PY_VER="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

    # onnxruntime-gpu uses dlopen() and ignores LD_LIBRARY_PATH — patch its RPATH.
    local ONNX_SO="${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so"
    if [[ -f "$ONNX_SO" ]]; then
        echo "[xense] Fixing onnxruntime-gpu RPATH..."
        uv pip install patchelf
        patchelf --set-rpath "${CONDA_PREFIX}/lib" "$ONNX_SO"
        echo "[xense] RPATH set: $(patchelf --print-rpath "$ONNX_SO")"
    fi

    # OpenCV's bundled Qt plugin causes XCB errors inside conda envs.
    local QXCB="${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
    if [[ -f "$QXCB" ]]; then
        echo "[xense] Removing OpenCV bundled Qt plugin: $QXCB"
        rm -f "$QXCB"
    fi

    echo "[xense] Done. Verify with: python -c 'import xensesdk; print(xensesdk)'"
}

# ── Hardware module: Franka Research 3 ───────────────────────────────────────

install_franka() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " Franka Research 3 (pylibfranka)  →  websockets"
    echo "══════════════════════════════════════════"

    local SDK_DIR="$PROJECT_ROOT/third_party/xense_franka"

    if [[ ! -d "$SDK_DIR" ]]; then
        echo "ERROR: $SDK_DIR not found."
        echo "  Run: git submodule update --init third_party/xense_franka"
        return 1
    fi

    uv pip install \
        "websockets>=12.0" \
        "pylibfranka==0.20.3"

    uv pip install -e "$SDK_DIR"

    echo "[franka] Done. Verify with: python -c 'import websockets; print(websockets.__version__)'"
}

# ── Hardware module: SpaceMouse ───────────────────────────────────────────────

install_spacemouse() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " SpaceMouse — pyspacemouse"
    echo "══════════════════════════════════════════"

    # Install hidapi system library for pyspacemouse
    if ! dpkg -l | grep -q libhidapi-dev; then
        echo "[spacemouse] Installing libhidapi-dev..."
        sudo apt-get update && sudo apt-get install -y libhidapi-dev
    fi

    # Setup udev rules for SpaceMouse HID access (allows non-root users)
    local UDEV_RULE_FILE="/etc/udev/rules.d/99-hidraw-permissions.rules"
    if [[ ! -f "$UDEV_RULE_FILE" ]]; then
        echo "[spacemouse] Setting up udev rules for HID access..."
        echo 'KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev"' | sudo tee "$UDEV_RULE_FILE" > /dev/null
        sudo udevadm control --reload-rules
        sudo udevadm trigger
    fi

    # Add user to plugdev group if not already a member
    if ! groups "$USER" | grep -q plugdev; then
        echo "[spacemouse] Adding user '$USER' to plugdev group..."
        sudo usermod -aG plugdev "$USER"
        echo "[spacemouse] WARN: You may need to log out and log back in for group changes to take effect."
    fi

    uv pip install pyspacemouse
    echo "[spacemouse] Done."
}

# ── Argument parsing ──────────────────────────────────────────────────────────

# Check if an environment name is provided
if [[ -n "$2" ]]; then
    ENV_NAME="$2"
else
    ENV_NAME="lerobot-xense"
fi

# Check if the --conda parameter is passed
if [[ "$1" == "--conda" ]]; then
    # Initialize conda
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    elif [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/anaconda3/etc/profile.d/conda.sh"
    else
        echo "Conda initialization script not found. Please install Miniconda3 or Anaconda3 or Miniforge3."
        exit 1
    fi
    create_environment "conda" "$ENV_NAME"

# Check if the --mamba parameter is passed
elif [[ "$1" == "--mamba" ]]; then
    # Initialize mamba (miniforge)
    if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniforge3/etc/profile.d/conda.sh"
    elif [ -f "$HOME/mambaforge/etc/profile.d/conda.sh" ]; then
        . "$HOME/mambaforge/etc/profile.d/conda.sh"
    else
        echo "Mamba initialization script not found. Please install Miniforge3 or Mambaforge."
        exit 1
    fi
    # Also source mamba.sh if available for full mamba support
    if [ -f "$HOME/miniforge3/etc/profile.d/mamba.sh" ]; then
        . "$HOME/miniforge3/etc/profile.d/mamba.sh"
    elif [ -f "$HOME/mambaforge/etc/profile.d/mamba.sh" ]; then
        . "$HOME/mambaforge/etc/profile.d/mamba.sh"
    fi
    create_environment "mamba" "$ENV_NAME"

# Check if the --install parameter is passed
elif [[ "$1" == "--install" ]]; then
    # Get the currently activated conda environment name
    if [[ -z "${CONDA_DEFAULT_ENV}" ]]; then
        echo "Error: No conda/mamba environment is currently activated."
        echo "Please activate an environment first with: conda/mamba activate <env_name>"
        exit 1
    fi
    ENV_NAME=${CONDA_DEFAULT_ENV}

    # Detect conda/mamba command
    if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
        CONDA_CMD="mamba"
    else
        CONDA_CMD="conda"
    fi

    echo "[INFO] Updating conda environment '$ENV_NAME' from: $CONDA_ENV_FILE"
    if ! $CONDA_CMD env update -f "$CONDA_ENV_FILE" -n "$ENV_NAME"; then
        echo "[ERROR] Failed to update conda environment '$ENV_NAME' from: $CONDA_ENV_FILE"
        exit 1
    fi

    echo -e "\n[INFO] Conda dependencies installed/updated for '$ENV_NAME'.\n"
    pip install uv
    uv pip install --upgrade pip
    # Ensure editable installs (PEP 660) work: setuptools must provide build_editable
    uv pip install --upgrade "setuptools>=71.0.0,<81.0.0" wheel

    # Workaround for Python ctypes.util.find_library("udev") on conda envs
    fix_udev_discovery

    # project root directory
    PROJECT_ROOT=$(pwd)

    echo "[INFO] Installing Lerobot from pyproject.toml"
    if uv pip install -e .; then
        echo "[INFO] Lerobot installed successfully!"
    else
        echo "[ERROR] Lerobot installation failed. See the error output above."
        exit 1
    fi

    # Verify critical package versions
    echo "[INFO] Verifying package versions..."
    AV_VER=$(python -c "import av; print(av.__version__)" 2>/dev/null || echo "NOT INSTALLED")
    TORCH_VER=$(python -c "import torch; print(torch.__version__)" 2>/dev/null || echo "NOT INSTALLED")
    echo "  - torch: $TORCH_VER"
    echo "  - av (pyav): $AV_VER (should be 15.1.0)"

    if [[ "$AV_VER" != "15.1.0" ]]; then
        echo "[WARN] av (pyav) version mismatch! Expected 15.1.0, got $AV_VER"
        uv pip install av==15.1.0 --force-reinstall
    fi

    echo ""
    echo "[INFO] Installing hardware SDK bindings..."
    echo ""

    install_arx5      || echo "[WARN] arx5 installation skipped or failed (see above)"
    install_flexiv    || echo "[WARN] flexiv installation skipped or failed (see above)"
    install_franka    || echo "[WARN] franka installation skipped or failed (see above)"
    ( install_pico4 ) || echo "[WARN] pico4 installation skipped or failed (see above)"
    install_xense     || echo "[WARN] xense installation skipped or failed (see above)"
    install_spacemouse || echo "[WARN] spacemouse installation skipped or failed (see above)"

    echo ""
    echo "[INFO] Lerobot-Xense installation completed successfully!"
    exit 0
else
    echo "Invalid argument. Usage:"
    echo "  --conda [env_name]   Create a conda environment (requires Miniconda/Anaconda)"
    echo "  --mamba [env_name]   Create a mamba environment (requires Miniforge)"
    echo "  --install            Install the package in the currently activated environment"
    exit 1
fi
