# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
# Copyright 2026 XenseRobotics Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.
"""

from concurrent.futures import ThreadPoolExecutor
import threading
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import (
    RealSenseCameraConfig,
)  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import (
    aggregate_pipeline_dataset_features,
    create_initial_features,
)
from lerobot.datasets.utils import (
    build_dataset_frame,
    combine_feature_dicts,
    hw_to_dataset_features,
)
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    arx5_follower,  # noqa: F401
    # bi_arx5,
    bi_flexiv_rizon4_rt,  # noqa: F401
    flexiv_rizon4,  # noqa: F401
    flexiv_rizon4_rt,  # noqa: F401
    make_robot_from_config,
    pylibfranka_research3,  # noqa: F401
    xense_flare,  # noqa: F401
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_pico4,
    btgamepad,
    gamepad,
    make_teleoperator_from_config,
    pico4,
    trlc_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop

# Import mock_teleop to register its config with draccus ChoiceRegistry
try:
    from lerobot.teleoperators.mock_teleop import MockTeleopConfig  # noqa: F401
except ImportError:
    # If tests are not available, mock_teleop won't be available
    pass
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    refresh_listener_events,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_devices
from lerobot.utils.robot_utils import busy_wait, get_logger
from lerobot.utils.utils import (
    get_safe_torch_device,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data

logger = get_logger("lerobot_record")


RAW_PASSTHROUGH_RECORD_PAIRS = frozenset(
    {
        ("flexiv_rizon4", "pico4"),
        ("flexiv_rizon4", "btgamepad"),
        ("flexiv_rizon4_rt", "pico4"),
        ("bi_flexiv_rizon4_rt", "bi_pico4"),
        ("pylibfranka_research3", "pico4"),
        ("pylibfranka_research3", "btgamepad"),
    }
)


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 1200
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec to use for encoding. Options: 'h264', 'hevc', 'libsvtav1', 'auto', or HW encoder name.
    # 'auto' probes the system and picks the best available hardware encoder, falling back to libsvtav1.
    vcodec: str = "libsvtav1"
    # Encode frames in real-time while recording (streaming encoding).
    # Dramatically reduces save_episode() latency. Recommended when hardware encoding is available.
    streaming_encoding: bool = False
    # Maximum number of frames to buffer per camera when streaming encoding is active (~1 s @ 30 fps).
    encoder_queue_maxsize: int = 30
    # Number of threads per encoder process (None = codec default).
    encoder_threads: int | None = None
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(
                policy_path, cli_overrides=cli_overrides
            )
            self.policy.pretrained_path = policy_path

        # XenseFlare acts as both robot and teleoperator (provides actions via get_action())
        # so it doesn't need a separate teleoperator or policy
        if self.teleop is None and self.policy is None:
            if self.robot.type != "xense_flare":
                raise ValueError(
                    "Choose a policy, a teleoperator or both to control the robot"
                )

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


def extract_joint_positions(obs):
    """提取关节位置，排除摄像头数据"""
    joint_positions = {}
    for key, value in obs.items():
        if (
            key.endswith(".pos")
            and not key.startswith("head")
            and not key.startswith("left_wrist")
            and not key.startswith("right_wrist")
        ):
            joint_positions[key] = value
    return joint_positions


def apply_velocity_limits(
    current_action: dict, prev_action: dict, dt: float, robot=None
) -> dict:
    """Apply velocity limits to action to ensure consistency with inference-time clipping.

    This ensures that recorded actions are physically executable during policy inference.

    Args:
        current_action: Current action dictionary with joint positions
        prev_action: Previous action dictionary with joint positions
        dt: Time step between actions (typically 1/fps)
        robot: Robot instance to get velocity limits from robot_configs

    Returns:
        Velocity-limited action dictionary
    """
    if prev_action is None:
        return current_action

    # Get velocity limits from robot config to ensure consistency with C++ settings
    if robot is not None and hasattr(robot, "robot_configs"):
        # Read from robot config (same as C++ controller uses)
        left_config = robot.robot_configs["left_config"]
        joint_vel_limits = (
            left_config.joint_vel_max.tolist()
        )  # Convert numpy array to list
        gripper_vel_limit = left_config.gripper_vel_max
    else:
        # Fallback to hardcoded values if robot config not available
        # From config.h: [20.0, 20.0, 20.5, 20.5, 20.0, 20.0] rad/s, gripper: 0.3 m/s
        joint_vel_limits = [20.0, 20.0, 20.5, 20.5, 20.0, 20.0]  # rad/s
        gripper_vel_limit = 0.3  # m/s

    limited_action = current_action.copy()
    clip_count = 0

    # Apply joint velocity limits
    for i in range(6):
        left_key = f"left_joint_{i+1}.pos"
        right_key = f"right_joint_{i+1}.pos"

        for key in [left_key, right_key]:
            if key in current_action and key in prev_action:
                current_pos = current_action[key]
                prev_pos = prev_action[key]
                delta_pos = current_pos - prev_pos
                max_delta = joint_vel_limits[i] * dt

                if abs(delta_pos) > max_delta:
                    # Clip to maximum allowed change
                    sign = 1 if delta_pos > 0 else -1
                    limited_action[key] = prev_pos + sign * max_delta
                    clip_count += 1
                    logger.debug(
                        f"Clipped {key}: {delta_pos:.3f} -> {sign * max_delta:.3f} rad"
                    )

    # Apply gripper velocity limits
    for gripper_key in ["left_gripper.pos", "right_gripper.pos"]:
        if gripper_key in current_action and gripper_key in prev_action:
            current_pos = current_action[gripper_key]
            prev_pos = prev_action[gripper_key]
            delta_pos = current_pos - prev_pos
            max_delta = gripper_vel_limit * dt

            if abs(delta_pos) > max_delta:
                # Clip to maximum allowed change
                sign = 1 if delta_pos > 0 else -1
                limited_action[gripper_key] = prev_pos + sign * max_delta
                clip_count += 1
                logger.debug(
                    f"Clipped {gripper_key}: {delta_pos:.3f} -> {sign * max_delta:.3f} m"
                )

    if clip_count > 0:
        logger.debug(f"Applied velocity limits: {clip_count} joints clipped")

    return limited_action


def _start_reset_in_background(robot, teleop, set_done):
    """Run robot.reset_to_initial_position() in a daemon thread.

    Calls set_done() in the finally block so the caller can clear any
    resetting flag regardless of success or failure.
    """
    logger.info("Starting reset_to_initial_position in background (A button pressed)...")

    def _thread():
        try:
            robot.reset_to_initial_position()
            logger.info("✅ reset_to_initial_position completed")
            tcp = robot.get_current_tcp_pose_quat()
            teleop.reset_to_pose(tcp[:7], tcp[7])
        except Exception as e:
            logger.error(f"Error during reset_to_initial_position: {e}")
        finally:
            set_done()

    threading.Thread(target=_thread, daemon=True).start()


def _sync_rt_teleop_to_robot_pose(robot: Robot, teleop: Teleoperator | None) -> None:
    if teleop is None or not hasattr(teleop, "reset_to_pose"):
        return

    if teleop.name == "bi_pico4":
        left_pose, right_pose = robot.get_current_tcp_pose_quat()
        teleop.reset_to_pose(
            left_pose[:7], right_pose[:7], left_pose[7], right_pose[7]
        )
    elif teleop.name in {"pico4", "btgamepad"}:
        pose = robot.get_current_tcp_pose_quat()
        teleop.reset_to_pose(pose[:7], pose[7])


def _use_raw_passthrough_record(robot_type: str, teleop_type: str | None) -> bool:
    return (robot_type, teleop_type) in RAW_PASSTHROUGH_RECORD_PAIRS


def _build_raw_passthrough_dataset_features(
    robot: Robot, use_videos: bool
) -> dict[str, dict]:
    return combine_feature_dicts(
        hw_to_dataset_features(robot.action_features, ACTION, use_videos),
        hw_to_dataset_features(robot.observation_features, OBS_STR, use_videos),
    )


@safe_stop_image_writer
def bi_arx5_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    """
    Specialized record loop for BiARX5 robot supporting both policy and manual demonstration modes.

    Policy mode:
    - Uses current observation for policy inference
    - Saves current observation with actually sent action (no shifting)
    - All frames are saved to dataset

    Manual demonstration mode with action shifting:
    - Frame 0: Only records observation, no dataset entry created
    - Frame 1+: Creates dataset entry using prev_observation and current joint positions as action
    - Last frame: Gets discarded (no dataset entry)

    This is optimized for dual-arm robots where the human manually moves the robot arms
    while in gravity compensation mode, and the system records the joint positions as demonstrations.

    Action shifting in manual mode ensures that action[t] corresponds to the state that will be reached at time t+1.
    """

    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    # Set appropriate control mode based on operation type
    if policy is not None:
        logger.info("Starting BiARX5 record loop for policy inference")
        # Policy mode: switch to normal position control for precise action execution
        robot.set_to_normal_position_control()
        policy.reset()

    # Reset processor if they are provided
    if preprocessor is not None and postprocessor is not None:
        preprocessor.reset()
        postprocessor.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()

    # Variables for action shifting (only used in manual demonstration mode)
    prev_observation = None
    prev_observation_frame = None

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        refresh_listener_events(events)

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Handle rerecord_episode event (same as standard record_loop)
        if events["rerecord_episode"]:
            # Don't reset the event here - let the main record() function handle it
            logger.info("Re-record episode requested, exiting record loop early")
            break

        # Handle go_home event for BiARX5 robot when recording (non-blocking)
        if events["go_start"] and policy is None:
            events["go_start"] = False
            logger.info(
                "Starting smooth_go_start in background while recording continues..."
            )

            # Execute smooth_go_start in a separate thread to avoid blocking
            def go_start_thread():
                try:
                    robot.smooth_go_start(duration=3.0)
                    logger.info(
                        "✅ smooth_go_start completed successfully in 2 seconds"
                    )
                except Exception as e:
                    logger.error(f"Error during smooth_go_start: {e}")

            threading.Thread(target=go_start_thread, daemon=True).start()

        # Get robot observation
        current_observation = robot.get_observation()
        current_observation_processed = robot_observation_processor(current_observation)
        current_observation_frame = None

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor

        if policy is not None or dataset is not None:
            current_observation_frame = build_dataset_frame(
                dataset.features, current_observation_processed, prefix=OBS_STR
            )

        # Get action from either policy or teleop
        if (
            policy is not None
            and preprocessor is not None
            and postprocessor is not None
        ):
            action_values = predict_action(
                observation=current_observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            current_action = {
                key: action_values[i].item()
                for i, key in enumerate(robot.action_features)
            }

            sent_action = robot.send_action(current_action)
            if dataset is not None:
                action_frame = build_dataset_frame(
                    dataset.features, sent_action, prefix=ACTION
                )
                frame = {
                    **current_observation_frame,
                    **action_frame,
                    "task": single_task,
                }
                dataset.add_frame(frame)
        else:
            current_action = extract_joint_positions(current_observation)
            # Action shifting logic: from second frame onwards, create dataset entries
            if prev_observation is not None and dataset is not None:
                # Manual demonstration mode with action shifting
                # Use current frame's joint positions as previous frame's action

                # Apply velocity limits to ensure consistency with inference-time clipping
                prev_action = extract_joint_positions(prev_observation)
                limited_current_action = apply_velocity_limits(
                    current_action, prev_action, 1.0 / fps, robot
                )
                action_frame = build_dataset_frame(
                    dataset.features, limited_current_action, prefix=ACTION
                )
                frame = {**prev_observation_frame, **action_frame, "task": single_task}
                dataset.add_frame(frame)

        if display_data:
            display_action = (
                extract_joint_positions(current_observation_processed)
                if policy is None
                else {}
            )
            log_rerun_data(
                observation=current_observation_processed, action=display_action
            )

        # Update for next iteration
        prev_observation = current_observation
        prev_observation_frame = current_observation_frame

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@safe_stop_image_writer
def xense_flare_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    """
    Record loop for XenseFlare data collection gripper.

    XenseFlare is special because it acts as both:
    - A robot (provides observation: camera, tactile, gripper position)
    - A teleoperator (provides action: Vive Tracker pose + gripper position)

    The action comes from robot.get_action() instead of a separate teleoperator.
    """
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    timestamp = 0
    start_episode_t = time.perf_counter()

    # Variables for action shifting (only used in manual demonstration mode)
    prev_observation = None
    prev_observation_frame = None

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        refresh_listener_events(events)

        if events["exit_early"]:
            events["exit_early"] = False
            break

        if events["rerecord_episode"]:
            logger.info("Re-record episode requested, exiting record loop early")
            break

        # Get robot observation (camera, tactile, gripper position)
        current_observation = robot.get_observation()
        current_observation_frame = None

        if dataset is not None:
            current_observation_frame = build_dataset_frame(
                dataset.features, current_observation, prefix=OBS_STR
            )

        current_action = robot.get_action()

        if prev_observation is not None and dataset is not None:
            # Manual demonstration mode with action shifting
            # Use current frame's action as previous frame's action
            current_action_frame = build_dataset_frame(
                dataset.features, current_action, prefix=ACTION
            )

            frame = {
                **prev_observation_frame,
                **current_action_frame,
                "task": single_task,
            }
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=current_observation, action=current_action)

        # Update for next iteration
        prev_observation = current_observation
        prev_observation_frame = current_observation_frame

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@safe_stop_image_writer
def flexiv_rizon4_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    if isinstance(teleop, list):
        raise ValueError("Multi-teleop mode is not supported in this version.")

    if policy is not None or preprocessor is not None or postprocessor is not None:
        raise ValueError(
            "Flexiv passthrough record mode is teleop-only. "
            "Do not provide policy or processor overrides."
        )

    timestamp = 0
    start_episode_t = time.perf_counter()
    is_resetting = False

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        refresh_listener_events(events)

        if events["exit_early"]:
            events["exit_early"] = False
            break

        if events["rerecord_episode"]:
            logger.info("Re-record episode requested, exiting record loop early")
            break

        # Snapshot reset flag once per iteration to avoid race conditions
        resetting_this_frame = is_resetting

        # Get robot observation (always runs, even during reset)
        current_observation = robot.get_observation()
        current_observation_frame = None

        if dataset is not None:
            current_observation_frame = build_dataset_frame(
                dataset.features, current_observation, prefix=OBS_STR
            )

        if isinstance(teleop, Teleoperator):
            robot_action_to_send = teleop.get_action()

            if events["go_start"]:
                events["go_start"] = False
                if (
                    hasattr(robot, "reset_to_initial_position")
                    and not resetting_this_frame
                ):
                    is_resetting = True

                    def _clear_reset():
                        nonlocal is_resetting
                        is_resetting = False

                    _start_reset_in_background(robot, teleop, set_done=_clear_reset)

                    if display_data:
                        log_rerun_data(observation=current_observation)

                    dt_s = time.perf_counter() - start_loop_t
                    busy_wait(1 / fps - dt_s)
                    timestamp = time.perf_counter() - start_episode_t
                    continue
        else:
            logger.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            dt_s = time.perf_counter() - start_loop_t
            busy_wait(1 / fps - dt_s)
            timestamp = time.perf_counter() - start_episode_t
            continue

        if resetting_this_frame:
            if display_data:
                log_rerun_data(observation=current_observation)

            dt_s = time.perf_counter() - start_loop_t
            busy_wait(1 / fps - dt_s)
            timestamp = time.perf_counter() - start_episode_t
            continue

        sent_action = robot.send_action(robot_action_to_send)

        if dataset is not None:
            action_frame = build_dataset_frame(
                dataset.features, sent_action, prefix=ACTION
            )
            frame = {
                **current_observation_frame,
                **action_frame,
                "task": single_task,
            }
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=current_observation, action=sent_action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@safe_stop_image_writer
def flexiv_rizon4_rt_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    if isinstance(teleop, list):
        raise ValueError("Multi-teleop mode is not supported in this version.")

    if policy is not None or preprocessor is not None or postprocessor is not None:
        raise ValueError(
            "Flexiv RT passthrough record mode is teleop-only. "
            "Do not provide policy or processor overrides."
        )

    timestamp = 0
    start_episode_t = time.perf_counter()
    prev_rt_moving = False
    prev_observation_frame = None  # for shifted-frame logic during RT reset

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        reset_triggered = False
        refresh_listener_events(events)

        if events["stop_recording"]:
            logger.info("Stop recording requested, exiting record loop early")
            break

        if events["rerecord_episode"]:
            logger.info("Re-record episode requested, exiting record loop early")
            break

        if events["exit_early"]:
            events["exit_early"] = False
            logger.info("Exit early requested, exiting record loop early")
            break

        if events["go_start"]:
            events["go_start"] = False
            if hasattr(robot, "reset_to_initial_position"):
                try:
                    logger.info("Reset to initial position (keyboard or controller button)")
                    robot.reset_to_initial_position()
                    reset_triggered = True
                except Exception as e:
                    logger.error(f"Error during reset_to_initial_position: {e}")

        current_observation = robot.get_observation()
        current_observation_frame = None

        if dataset is not None:
            current_observation_frame = build_dataset_frame(
                dataset.features, current_observation, prefix=OBS_STR
            )

        robot_is_moving = hasattr(robot, "rt_moving") and robot.rt_moving
        if robot_is_moving:
            prev_rt_moving = True

        if prev_rt_moving:
            if not robot_is_moving:
                prev_rt_moving = False
                try:
                    _sync_rt_teleop_to_robot_pose(robot, teleop)
                    logger.info("Synced teleop to robot pose after RT reset")
                except Exception as e:
                    logger.error(f"Failed to sync teleop after RT reset: {e}")

        if isinstance(teleop, Teleoperator):
            teleop_action = teleop.get_action()

            if reset_triggered:
                sent_action = teleop_action  # not sent, used only for display
            elif robot_is_moving:
                sent_action = teleop_action  # not sent, used only for display
            else:
                sent_action = robot.send_action(teleop_action)

            teleop_is_active = not hasattr(teleop, "is_active") or teleop.is_active()

            if dataset is not None and not reset_triggered and teleop_is_active:
                if robot_is_moving and prev_observation_frame is not None:
                    # Shifted-frame logic during RT reset: C++ background thread controls
                    # the arm autonomously — Python does not send arm commands.
                    # Action = proprioception state from current obs (same keys as action_features:
                    # left/right TCP pose 9D + gripper 1D = 20D). Images and other obs keys are
                    # excluded because we iterate over robot.action_features, not current_observation.
                    current_as_action = {
                        k: current_observation[k]
                        for k in robot.action_features
                        if k in current_observation
                    }
                    action_frame = build_dataset_frame(
                        dataset.features, current_as_action, prefix=ACTION
                    )
                    frame = {**prev_observation_frame, **action_frame, "task": single_task}
                    dataset.add_frame(frame)
                elif not robot_is_moving:
                    # Normal teleop: direct frame (obs[t], sent_action[t]).
                    action_frame = build_dataset_frame(
                        dataset.features, sent_action, prefix=ACTION
                    )
                    frame = {
                        **current_observation_frame,
                        **action_frame,
                        "task": single_task,
                    }
                    dataset.add_frame(frame)

            # Only advance prev_observation_frame when actively recording.
            # When grip is released, reset it to None so the next enabled frame
            # starts a fresh trajectory segment without a stale prev anchor.
            if teleop_is_active:
                prev_observation_frame = current_observation_frame
            else:
                prev_observation_frame = None
            display_action = sent_action
        else:
            logger.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )

            dt_s = time.perf_counter() - start_loop_t
            busy_wait(1 / fps - dt_s)
            timestamp = time.perf_counter() - start_episode_t
            continue

        if display_data:
            log_rerun_data(observation=current_observation, action=display_action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@safe_stop_image_writer
def pylibfranka_research3_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    if isinstance(teleop, list):
        raise ValueError("Multi-teleop mode is not supported in this version.")

    timestamp = 0
    start_episode_t = time.perf_counter()

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        refresh_listener_events(events)

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        current_observation = robot.get_observation()
        current_observation_frame = None

        if dataset is not None:
            current_observation_frame = build_dataset_frame(
                dataset.features, current_observation, prefix=OBS_STR
            )

        if isinstance(teleop, Teleoperator):
            act = teleop.get_action()
        else:
            logger.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        robot_action_to_send = act

        if events["go_start"]:
            events["go_start"] = False
            if hasattr(robot, "reset_to_initial_position"):
                robot.reset_to_initial_position()
            logger.info("Reset to initial position (keyboard or controller button)")

            if hasattr(teleop, "reset_to_pose"):
                current_pose_quat = robot.get_current_tcp_pose_quat()
                teleop.reset_to_pose(current_pose_quat[:7], current_pose_quat[7])
            continue

        # Send action to robot
        sent_action = robot.send_action(robot_action_to_send)

        if dataset is not None:
            action_frame = build_dataset_frame(
                dataset.features, sent_action, prefix=ACTION
            )
            frame = {
                **current_observation_frame,
                **action_frame,
                "task": single_task,
            }
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=current_observation, action=sent_action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t

@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    if isinstance(teleop, list):
        raise ValueError("Multi-teleop mode is not supported in this version.")

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    is_resetting = False
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        refresh_listener_events(events)

        if events["exit_early"]:
            events["exit_early"] = False
            break

        if is_resetting:
            dt_s = time.perf_counter() - start_loop_t
            busy_wait(1 / fps - dt_s)
            timestamp = time.perf_counter() - start_episode_t
            continue

        # Get robot observation
        obs = robot.get_observation()

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(
                dataset.features, obs_processed, prefix=OBS_STR
            )

        # Get action from either policy or teleop
        if (
            policy is not None
            and preprocessor is not None
            and postprocessor is not None
        ):
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            act_processed_policy: RobotAction = make_robot_action(
                action_values, dataset.features
            )

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        else:
            logger.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        if (
            events["go_start"]
            and isinstance(teleop, Teleoperator)
            and teleop.name == "pico4"
            and robot.name == "flexiv_rizon4"
        ):
            events["go_start"] = False
            if hasattr(robot, "reset_to_initial_position"):
                is_resetting = True

                def _clear_reset():
                    nonlocal is_resetting
                    is_resetting = False

                _start_reset_in_background(robot, teleop, set_done=_clear_reset)
                continue

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        _sent_action = robot.send_action(robot_action_to_send)

        # print(f"Action to send: {robot_action_to_send}")

        # Write to dataset
        if dataset is not None:
            action_frame = build_dataset_frame(
                dataset.features, action_values, prefix=ACTION
            )
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=obs_processed, action=action_values)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@safe_stop_image_writer
def arx5_trlc_record_loop(
    robot: Robot,
    teleop: Teleoperator | None,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],
    dataset: LeRobotDataset | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    """
    Record loop for ARX5 follower robot teleoperated with TRLC leader, with optional policy inference.

    Teleop mode:
    - TRLC action keys are filtered to match robot.action_features.
    - Raw gripper value is converted: gripper_cmd = (1 - raw_gripper) * 1.57.
    - Observation and the actually sent action are recorded each frame (no action shifting).

    Policy mode:
    - Standard policy inference via predict_action().
    - Observation and sent action are recorded each frame (no action shifting).
    """
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    robot_action_keys = set(robot.action_features.keys())
    warned_unmapped_keys = False

    timestamp = 0
    start_episode_t = time.perf_counter()

    while timestamp < control_time_s:
        loop_start = time.perf_counter()
        refresh_listener_events(events)

        if events["exit_early"]:
            events["exit_early"] = False
            break

        if events["rerecord_episode"]:
            logger.info("Re-record episode requested, exiting record loop early")
            break

        obs = robot.get_observation()
        obs_processed = robot_observation_processor(obs)

        if dataset is not None:
            observation_frame = build_dataset_frame(
                dataset.features, obs_processed, prefix=OBS_STR
            )

        if policy is not None and preprocessor is not None and postprocessor is not None:
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
            robot_action_to_send = robot_action_processor(
                (make_robot_action(action_values, dataset.features), obs)
            )
        elif teleop is not None:
            raw_action = teleop.get_action()
            for k in list(raw_action.keys()):
                if "gripper" in k:
                    raw_action[k] = (1 - raw_action[k]) * 1.57

            teleop_action = teleop_action_processor((raw_action, obs))
            filtered_action = {k: v for k, v in teleop_action.items() if k in robot_action_keys}

            if len(filtered_action) != len(teleop_action) and not warned_unmapped_keys:
                dropped = sorted(set(teleop_action) - robot_action_keys)
                logger.warn(
                    f"TRLC action keys not present in ARX5 action schema, dropping: {dropped}"
                )
                warned_unmapped_keys = True

            if not filtered_action:
                raise ValueError(
                    "No overlapping action keys between TRLC leader output and ARX5 action schema. "
                    "Check robot.control_mode (TRLC requires joint-style keys like joint_i.pos, gripper.pos)."
                )

            robot_action_to_send = robot_action_processor((filtered_action, obs))
        else:
            logger.warning("No policy or teleop provided, skipping action.")
            dt_s = time.perf_counter() - loop_start
            busy_wait(1 / fps - dt_s)
            timestamp = time.perf_counter() - start_episode_t
            continue

        sent_action = robot.send_action(robot_action_to_send)

        if dataset is not None:
            action_frame = build_dataset_frame(
                dataset.features, sent_action, prefix=ACTION
            )
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=obs_processed, action=robot_action_to_send)

        dt_s = time.perf_counter() - loop_start
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    logger.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording")

    teleop_type = cfg.teleop.type if cfg.teleop is not None else None
    use_raw_passthrough_record = _use_raw_passthrough_record(
        cfg.robot.type, teleop_type
    )

    if use_raw_passthrough_record and cfg.policy is not None:
        raise ValueError(
            f"{cfg.robot.type} + {teleop_type} record uses raw teleop passthrough only. "
            "Do not provide --policy.* for this record flow."
        )

    robot = make_robot_from_config(cfg.robot)
    teleop = (
        make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None
    )

    teleop_action_processor, robot_action_processor, robot_observation_processor = (
        make_default_processors()
    )

    if use_raw_passthrough_record:
        dataset_features = _build_raw_passthrough_dataset_features(
            robot, cfg.dataset.video
        )
    else:
        dataset_features = combine_feature_dicts(
            aggregate_pipeline_dataset_features(
                pipeline=teleop_action_processor,
                initial_features=create_initial_features(
                    action=robot.action_features
                ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
                use_videos=cfg.dataset.video,
            ),
            aggregate_pipeline_dataset_features(
                pipeline=robot_observation_processor,
                initial_features=create_initial_features(
                    observation=robot.observation_features
                ),
                use_videos=cfg.dataset.video,
            ),
        )

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
            vcodec=cfg.dataset.vcodec,
            streaming_encoding=cfg.dataset.streaming_encoding,
            encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
            encoder_threads=cfg.dataset.encoder_threads,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera
                * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(
            dataset, robot, cfg.dataset.fps, dataset_features
        )
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera
            * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
            vcodec=cfg.dataset.vcodec,
            streaming_encoding=cfg.dataset.streaming_encoding,
            encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
            encoder_threads=cfg.dataset.encoder_threads,
        )

    if not cfg.dataset.streaming_encoding:
        logger.info(
            "Streaming encoding is disabled. For faster episode saving, consider enabling: "
            "--dataset.streaming_encoding=true --dataset.encoder_threads=2"
        )

    # Load pretrained policy
    policy = (
        None
        if cfg.policy is None or use_raw_passthrough_record
        else make_policy(cfg.policy, ds_meta=dataset.meta)
    )
    preprocessor = None
    postprocessor = None
    if cfg.policy is not None and not use_raw_passthrough_record:
        preprocessor, postprocessor = make_pre_post_processors(
            policy_cfg=cfg.policy,
            pretrained_path=cfg.policy.pretrained_path,
            dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
            preprocessor_overrides={
                "device_processor": {"device": cfg.policy.device},
                "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
            },
        )

    if teleop_type == "pico4" and cfg.robot.type == "flexiv_rizon4":
        robot.connect(go_to_start=True)
        logger.info(f"Start EEF pose: {robot.get_current_tcp_pose_quat()}")
    elif teleop_type == "pico4" and cfg.robot.type == "flexiv_rizon4_rt":
        robot.connect(go_to_start=True)
        logger.info(f"Start EEF pose: {robot.get_current_tcp_pose_quat()}")
    elif (
        teleop_type == "bi_pico4"
        and cfg.robot.type == "bi_flexiv_rizon4_rt"
        and teleop is not None
    ):
        try:
            with ThreadPoolExecutor(max_workers=2) as executor:
                robot_future = executor.submit(robot.connect, go_to_start=True)
                teleop_future = executor.submit(teleop.pre_init)
                teleop_future.result()
                robot_future.result()
        except KeyboardInterrupt:
            logger.info("Startup interrupted by user")
            raise

        left_pose, right_pose = robot.get_current_tcp_pose_quat()
        logger.info(f"Left start pose:  {left_pose}")
        logger.info(f"Right start pose: {right_pose}")
    elif teleop_type == "pico4" and cfg.robot.type == "pylibfranka_research3":
        robot.connect(go_to_start=False)
        logger.info(f"Start EEF pose: {robot.get_current_tcp_pose_quat()}")
    else:
        robot.connect()
        # logger.info(f"Start EEF pose: {robot.get_current_tcp_pose_quat()}")

    if teleop is not None:
        if teleop_type == "pico4" and cfg.robot.type == "flexiv_rizon4":
            teleop.connect(current_tcp_pose_quat=robot.get_current_tcp_pose_quat())
            logger.info("Teleop initialized with robot EEF pose.")
        elif teleop_type == "btgamepad" and cfg.robot.type == "flexiv_rizon4":
            teleop.connect(current_tcp_pose_quat=robot.get_current_tcp_pose_quat())
            logger.info("Teleop initialized with robot EEF pose.")
        elif teleop_type == "pico4" and cfg.robot.type == "flexiv_rizon4_rt":
            teleop.connect(current_tcp_pose_quat=robot.get_current_tcp_pose_quat())
            logger.info("Teleop initialized with robot EEF pose.")
        elif (
            teleop_type == "bi_pico4"
            and cfg.robot.type == "bi_flexiv_rizon4_rt"
        ):
            left_pose, right_pose = robot.get_current_tcp_pose_quat()
            teleop.connect(left_tcp_pose_quat=left_pose, right_tcp_pose_quat=right_pose)
            logger.info("BiPico4 initialized with both robot EEF poses.")
        elif teleop_type == "pico4" and cfg.robot.type == "pylibfranka_research3":
            teleop.connect(current_tcp_pose_quat=robot.get_current_tcp_pose_quat())
            logger.info("Teleop initialized with robot EEF pose.")
        elif (
            teleop_type == "btgamepad"
            and cfg.robot.type == "pylibfranka_research3"
        ):
            teleop.connect(current_tcp_pose_quat=robot.get_current_tcp_pose_quat())
            logger.info("Teleop initialized with robot EEF pose.")
        else:
            teleop.connect()

    listener, events = init_keyboard_listener(teleop=teleop)

    try:
        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while (
                recorded_episodes < cfg.dataset.num_episodes
                and not events["stop_recording"]
            ):
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)

                # Use specialized record loop for XenseFlare (data collection gripper)
                if cfg.robot.type == "xense_flare":
                    xense_flare_record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                # Use specialized record loop for BiARX5 robot
                elif cfg.robot.type == "bi_arx5":
                    bi_arx5_record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=policy,
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                elif cfg.robot.type == "flexiv_rizon4":
                    flexiv_rizon4_record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop=teleop,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                elif cfg.robot.type in {"flexiv_rizon4_rt", "bi_flexiv_rizon4_rt"}:
                    flexiv_rizon4_rt_record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop=teleop,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                elif cfg.robot.type == "pylibfranka_research3":
                    pylibfranka_research3_record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop=teleop,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                elif cfg.robot.type == "arx5_follower":
                    arx5_trlc_record_loop(
                        robot=robot,
                        teleop=teleop,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        dataset=dataset,
                        policy=policy,
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                else:
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=policy,
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                # Execute a few seconds without recording to give time to manually reset the environment
                # Skip reset for the last episode to be recorded
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1)
                    or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)
                    if cfg.robot.type == "xense_flare":
                        xense_flare_record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )
                    elif cfg.robot.type == "bi_arx5":
                        bi_arx5_record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )
                    elif cfg.robot.type == "flexiv_rizon4":
                        flexiv_rizon4_record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )
                    elif cfg.robot.type in {"flexiv_rizon4_rt", "bi_flexiv_rizon4_rt"}:
                        flexiv_rizon4_rt_record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )
                    elif cfg.robot.type == "pylibfranka_research3":
                        pylibfranka_research3_record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )
                    elif cfg.robot.type == "arx5_follower":
                        arx5_trlc_record_loop(
                            robot=robot,
                            teleop=teleop,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )
                    else:
                        record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                dataset.save_episode()
                recorded_episodes += 1
                events["exit_early"] = False  # clear so the reset loop runs normally

        log_say("Stop recording", cfg.play_sounds, blocking=True)
    except KeyboardInterrupt:
        logger.info("\nKeyboardInterrupt received. Stopping recording...")
    except Exception as e:
        import traceback
        logger.error(f"Error during recording: {e}\n{traceback.format_exc()}")
    finally:
        # Always disconnect robot and teleop safely
        try:
            if robot.is_connected:
                logger.info("Disconnecting robot...")
                robot.disconnect()
                logger.info("✅ Robot disconnected safely")
        except Exception as e:
            logger.error(f"Error during robot disconnect: {e}")

        try:
            if (
                teleop is not None
                and hasattr(teleop, "is_connected")
                and teleop.is_connected
            ):
                logger.info("Disconnecting teleop...")
                teleop.disconnect()
                logger.info("✅ Teleop disconnected safely")
        except Exception as e:
            logger.error(f"Error during teleop disconnect: {e}")

        try:
            if not is_headless() and listener is not None:
                listener.stop()
        except Exception as e:
            logger.error(f"Error stopping listener: {e}")

        try:
            if cfg.dataset.push_to_hub:
                dataset.push_to_hub(
                    tags=cfg.dataset.tags,
                    private=cfg.dataset.private,
                    upload_large_folder=True,
                )
        except Exception as e:
            logger.error(f"Error pushing to hub: {e}")

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_devices()
    record()


if __name__ == "__main__":
    main()
