
import asyncio 
import numpy as np 
from xense_franka import RobotInterface, FrankaController
import time 

async def main(args):
    robot = RobotInterface(ip = args.ip if not args.sim else None) 
    controller = FrankaController(robot)
    
    controller.verbose = True

    await controller.start()

    # tests the 1kHz connection with the robot 
    # prints average frequency / jitter 
    await controller.test_connection()


    while True: 
        # this moves to certain position by offline trajectory generated by Ruckig
        await controller.move([0, 0, 0.0, -1.57079, 0, 1.57079, -0.7853])

        # you can switch controllers / set gains at run-time 
        controller.switch("impedance")
        controller.kp = np.ones(7) * 80.0
        controller.kd = np.ones(7) * 4.0
        # this enforces 50Hz update rate for impedance controller target
        controller.set_freq(50) 
        for cnt in range(100): 
            delta = np.sin(cnt / 50.0 * np.pi) * 0.1
            init = controller.initial_qpos
            await controller.set("q_desired", delta + init)

        # switch to osc controller
        controller.switch("osc")
        controller.set_freq(50)  

        for cnt in range(100): 
            delta = np.sin(cnt / 50.0 * np.pi) * 0.1
            init = controller.initial_ee 

            desired_ee = np.eye(4) 
            desired_ee[:3, :3] = init[:3, :3]
            desired_ee[:3, 3] = init[:3, 3] + np.array([0, delta, 0])

            await controller.set("ee_desired", desired_ee)

        await asyncio.sleep(1.0)

if __name__ == "__main__":

    import argparse 
    parser = argparse.ArgumentParser()
    parser.add_argument("--sim", action="store_true", help="use simulation")
    parser.add_argument("--ip", type=str, default="172.16.0.2")
    args = parser.parse_args()

    asyncio.run(main(args)) 
